### PR TITLE
fix for rebar3

### PR DESCRIPTION
**Pull request by benoitc**
this change add the pb plugin support so the nif can be built with rebar3.

### CODE REVIEW

**Comment by benoitc** [comment]
fix #3

**Comment by mremond** [comment]
Could it break build with rebar 2 ?

**Comment by mremond** [comment]
We will have to make the patch a bit different to support both rebar2 and rebar3 approach.

**Comment by prefiks** [comment]
I adapted your fix to apply it only when compilation is performed by rebar3 in commit a44ce7bf0f56881ed39c6c998d14d9b6fa66023d. Thank for your help!

**Pull request closed without merging**
